# Generated by Django 5.1.1 on 2024-10-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0002_article"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Article",
            new_name="Articles",
        ),
    ]
