# Generated by Django 5.1.1 on 2024-09-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0002_picture_remove_projects_image_projects_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="project_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
