# Generated by Django 5.1.1 on 2024-09-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0003_alter_projects_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="git_link",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="projects",
            name="live_link",
            field=models.URLField(null=True),
        ),
    ]
