# Generated by Django 5.1.1 on 2024-09-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0004_projects_git_link_projects_live_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="git_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
