# Generated by Django 5.1.1 on 2024-10-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0004_remove_articles_image_articles_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
